require("_options")
require("_keymaps")
require("_plugins")
require("_colorschemes")
require("_cmp")
require("_lsp")
require("_telescope")
require("_treesitter")
require("_autopairs")
require("_comment")
require("_gitsigns")
require("_nvim-tree")
require("_indentline")
require("_lualine")
require("_bufferline")
-- require("_project")
-- require("_impatient")
require("_neovim-session-manager")
-- require("autocommands")
