require("options")
require("keymaps")
require("plugins")
require("colorschemes")
require("cmp")
require("lsp")
-- require("telescope")
-- require("treesitter")
-- require("autopairs")
-- require("comment")
-- require("gitsigns")
-- require("nvim-tree")
-- require("lualine")
-- require("impatient")
-- require("indentline")
-- require("autocommands")
